-- PM Wiki content batch 20260912
-- 15 new pm_models + 45 pm_model_sources (draft)
-- DO NOT apply from this agent; parent handles Supabase/GitHub

INSERT INTO public.pm_models (
  status, category, manufacturer, model_name, slug, original_price, battery_replace_cost, tire_size, suspension_type, battery_voltage, weight, chronic_defects, used_checklist, affiliate_links, is_discontinued, motor_power_peak, battery_capacity, range_official, max_speed, brake_type, pros, cons, dimensions, charger_spec, release_year, safety_rules, one_line_summary, sub_model, bluetooth_enabled, battery_check_method, compatible_accessories, used_price_min, used_price_max, image_url, pm_score, nominal_voltage, battery_wh, motor_power_rated, max_load, charge_time, app_integration_available
) VALUES
(
  'draft',
  'ebike',
  'Aventon',
  'Aventon Pace 4 36V (20Ah)',
  'aventon-pace-4-36v-20ah',
  2159000,
  520000,
  27.5,
  '시트포스트 서스펜션(강성 포크)',
  36,
  26.4,
  '["강성 포크라 노면 충격이 손에 잘 전달됨", "4G/GPS 구독 만료 후 일부 보안 기능 유료화", "무게 대비 배터리 탈착이 초보에게는 다소 무거울 수 있음"]'::jsonb,
  '[{"title": "배터리 키리스 잠금·앱 연동", "description": "디스플레이/앱으로 배터리 잠금 해제와 GPS 위치 기록이 정상인지 확인"}, {"title": "유압 브레이크·E-컷오프", "description": "Tektro 유압 제동력과 브레이크 레버 모터 차단 작동 점검"}, {"title": "토크 센서·부스트 모드", "description": "페달 토크 반응과 Boost Mode 단시간 출력 상승이 작동하는지 확인"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  864,
  20,
  113,
  45,
  'Tektro 유압 디스크',
  '["토크 센서와 스마트 ACU(GPS·이락)로 도심 크루저 완성도 높음", "LG 733Wh 배터리로 실사용 장거리 출퇴근 여유", "스텝스루 프레임과 서스펜션 시트포스트로 승차감 우수"]'::jsonb,
  '["강성 포크라 거친 노면에서는 손 피로가 큼", "스마트 기능 유지를 위해 구독·앱 관리 필요", "국내 정식 AS 네트워크는 해외 직구 대비 제한적"]'::jsonb,
  '휠베이스 약 1085–1110mm / 27.5인치',
  '42V 4A (약 5시간)',
  2025,
  '["도로교통법상 전동킥보드·PM 규정이 아닌 전기자전거 분류 여부 확인", "헬멧 착용 권장", "야간 전조등·후미등 점등 필수"]'::jsonb,
  '스마트 보안과 토크 센서를 갖춘 Aventon의 신세대 도심 크루저 전기자전거.',
  'Step-Through',
  TRUE,
  '디스플레이 SOC 및 Aventon 앱에서 잔량·위치 확인',
  '[]'::jsonb,
  1500000,
  1950000,
  NULL,
  7,
  36,
  733,
  500,
  136,
  5,
  TRUE
),
(
  'draft',
  'ebike',
  'SUPER73',
  'SUPER73-S2 SE 48V (15Ah)',
  'super73-s2-se-48v-15ah',
  4246000,
  780000,
  20,
  '전방 조절식 / 후방 강성',
  48,
  32.2,
  '["싱글 스피드라 경사·고속 페달링 효율이 제한적", "무거운 모페드 스타일로 실내 보관·운반 부담", "앱 페어링 후 클래스 모드 제한 정책 변경 이력 있음"]'::jsonb,
  '[{"title": "배터리 UL2271·커넥터", "description": "48V 15Ah 배터리 외관 팽창·커넥터 산화·에러 코드 여부 확인"}, {"title": "전방 서스펜션·타이어", "description": "MAXXIS 팻타이어 마모와 전방 서스펜션 누유·유격 점검"}, {"title": "유압 브레이크", "description": "Tektro 2피스톤 유압 디스크 제동력과 오일 누유 확인"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  1200,
  15,
  72,
  32,
  'Tektro 유압 디스크 2피스톤',
  '["상징적인 모페드 스타일과 강한 가속감", "720Wh UL 인증 배터리로 도심 크루징에 충분", "팻타이어와 전방 서스펜션으로 노면 흡수 우수"]'::jsonb,
  '["가격 대비 싱글 스피드 구동계", "무게 32kg대로 계단·대중교통 이동 어려움", "국내 법규상 도로 이용 시 클래스·속도 제한 확인 필요"]'::jsonb,
  '약 175×63×107cm',
  '전용 충전기 (약 7–8시간)',
  2024,
  '["헬멧 필수", "사유지·허가 구간 외 고속 모드 사용 금지", "야간 조명 점등"]'::jsonb,
  '모페드 감성의 아이콘, SUPER73 S2 SE 레거시 시리즈 전기자전거.',
  'SE Legacy',
  TRUE,
  '디스플레이 잔량 및 SUPER73 앱 SOC 확인',
  '[]'::jsonb,
  2800000,
  3700000,
  NULL,
  4,
  48,
  720,
  750,
  147,
  7.5,
  TRUE
),
(
  'draft',
  'ebike',
  'Lectric',
  'Lectric ONE 48V (14Ah)',
  'lectric-one-48v-14ah',
  3239000,
  580000,
  20,
  '강성(벨트·기어박스 중심 도심형)',
  48,
  25,
  '["피니언 기어박스·벨트는 정비처가 제한적", "20인치 휠은 고속 안정감이 28인치 대비 낮을 수 있음", "고급 부품 구성이라 중고 부품 수급이 더딜 수 있음"]'::jsonb,
  '[{"title": "Gates 벨트·Pinion 변속", "description": "벨트 마모·장력과 기어박스 변속 소음·스마트시프트 동작 확인"}, {"title": "유압 브레이크 180mm", "description": "제동력과 브레이크 연동 후미등 점등 확인"}, {"title": "배터리 UL2271", "description": "48V 14Ah 배터리 팽창·충전 이상·앱/디스플레이 SOC 일치 여부"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  1310,
  14,
  97,
  45,
  '유압 디스크 180mm',
  '["유지보수 거의 없는 벨트+피니언 기어박스", "정숙한 750W급 허브와 도심 장거리 배터리", "유압 브레이크·브레이크 연동 후미등으로 안전성 우수"]'::jsonb,
  '["가격대가 XP 시리즈 대비 높음", "전문 정비 인프라가 국내에 부족", "폴딩 XP와 달리 휴대성은 낮음"]'::jsonb,
  '도심 커뮤터 지오메트리 / 20×2.5 타이어',
  '전용 48V 충전기',
  2024,
  '["헬멧 착용", "차도·자전거도로 이용 규정 준수", "야간 등화류 점등"]'::jsonb,
  '벨트 드라이브와 피니언 기어박스로 정비 부담을 줄인 Lectric 프리미엄 커뮤터.',
  'Long-Range',
  TRUE,
  '컬러 디스플레이 SOC 확인',
  '[]'::jsonb,
  2200000,
  2900000,
  NULL,
  6,
  48,
  672,
  750,
  150,
  6,
  FALSE
),
(
  'draft',
  'ebike',
  'Rad Power Bikes',
  'RadCity 5 Plus 48V (14Ah)',
  'radpower-radcity-5-plus-48v-14ah',
  2295000,
  550000,
  27.5,
  '전방 서스펜션 포크(약 50–80mm)',
  48,
  29.5,
  '["케이블 정리 마감이 지저분하다는 리뷰 다수", "좌측 보조 디스플레이 직사광선 가독성 저하", "부품 대체(시마노↔마이크로시프트)로 개체 편차 가능"]'::jsonb,
  '[{"title": "반통합형 배터리", "description": "48V 14Ah 배터리 잠금·충전 포트·팽창 여부 확인"}, {"title": "유압 디스크·랙", "description": "NUTT 등 유압 제동과 프레임 직결 리어랙 볼트 풀림 점검"}, {"title": "허브 모터·스로틀", "description": "750W 허브 이음·하프트위스트 스로틀 유격 확인"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  750,
  14,
  80,
  32,
  '유압 디스크 180mm',
  '["더치 스타일 업라이트 자세와 안정적 핸들링", "프레임 직결 리어랙·차일드시트 호환성", "유압 브레이크로 제동 테스트 평가 우수"]'::jsonb,
  '["클래스2 기본 20mph로 고속 출퇴근엔 답답할 수 있음", "케이블 마감·디스플레이 가독성 아쉬움", "총중량 약 65lb로 들고 다니기 무거움"]'::jsonb,
  '27.5×2.0 타이어 / 업라이트 커뮤터',
  '전용 48V 충전기',
  2021,
  '["헬멧 착용", "스로틀·PAS 속도는 현지 규정 준수", "야간 통합등 점등"]'::jsonb,
  '실용적인 더치 스타일 출퇴근용, Rad Power의 RadCity 5 Plus.',
  'Plus',
  FALSE,
  '듀얼 디스플레이 배터리 게이지 확인',
  '[]'::jsonb,
  1200000,
  1800000,
  NULL,
  5,
  48,
  672,
  750,
  125,
  6,
  FALSE
),
(
  'draft',
  'ebike',
  'Himiway',
  'Himiway Cobra D7 48V (20Ah)',
  'himiway-cobra-d7-48v-20ah',
  3374000,
  720000,
  26,
  '풀서스펜션(전방 에어/코일 + 후방 쇼크)',
  48,
  40.2,
  '["40kg급 헤비급이라 들어올리기·차량 적재 어려움", "팻타이어 구름저항으로 포장도로 효율 낮음", "고출력 허브라 장시간 급경사에서 발열 관리 필요"]'::jsonb,
  '[{"title": "풀서스펜션 누유", "description": "전방 포크·후방 쇼크 오일 누유와 유격 확인"}, {"title": "960Wh 배터리", "description": "삼성/LG 48V 20Ah 셀 팽창·잠금장치·잔량 정확도 점검"}, {"title": "1000W 허브·토크센서", "description": "모터 이상음과 토크센서 PAS 반응 확인"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  1000,
  20,
  129,
  45,
  'Tektro 유압 디스크',
  '["960Wh 대용량과 1000W급 허브로 험지·적재에 강함", "4바 링키지 풀서스로 충격 흡수 우수", "400lb급 페이로드로 장비 운반에 유리"]'::jsonb,
  '["무게가 매우 무거워 일상 휴대 부적합", "가격·부피 대비 도심 출퇴근에는 과잉 스펙", "국내 전기자전거 출력 규정과 충돌 가능"]'::jsonb,
  '전장 약 210cm / 26×4.5 팻타이어',
  '48V 3A 충전기',
  2022,
  '["사유지·허가된 오프로드 외 고출력 주행 자제", "헬멧·보호구 착용", "최대적재 초과 금지"]'::jsonb,
  '헌팅·오프로드용 풀서스 팻타이어, Himiway D7 Cobra.',
  'D7 Cobra',
  FALSE,
  'LCD 디스플레이 SOC 확인',
  '[]'::jsonb,
  2000000,
  2800000,
  NULL,
  5,
  48,
  960,
  1000,
  181,
  7,
  FALSE
),
(
  'draft',
  'ebike',
  'Mokwheel',
  'Mokwheel Asphalt 2.0 48V (14.7Ah)',
  'mokwheel-asphalt-2-0-48v-14-7ah',
  2024000,
  480000,
  27.5,
  '전방 에어 서스펜션 100mm',
  48,
  29,
  '["토크+케이던스 듀얼센서 설정 미숙 시 이질감", "직구 브랜드라 국내 공식 AS는 제한적", "디스플레이·펌웨어 개체 편차 리뷰 존재"]'::jsonb,
  '[{"title": "탈착 배터리", "description": "48V 14.7Ah 배터리 잠금·단자 부식·팽창 여부"}, {"title": "유압 브레이크", "description": "Tektro 유압 디스크 제동과 모터 컷오프 확인"}, {"title": "전방 100mm 포크", "description": "에어압·록아웃 작동과 누유 점검"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  860,
  14.7,
  97,
  45,
  'Tektro 유압 디스크',
  '["토크 센서 기반의 자연스러운 페달 어시스트", "펜더·랙 기본 포함으로 출퇴근 구성 탄탄", "UL 배터리와 IPX6급 생활 방수 표기"]'::jsonb,
  '["브랜드 인지도·국내 서비스망 약함", "무게 64lb대로 폴딩 모델 대비 보관 불리", "최고속도 언락 시 법규 확인 필수"]'::jsonb,
  '27.5×2.4 / 휠베이스 약 112cm',
  '48V 3A',
  2024,
  '["헬멧 착용", "도심 규정 속도 준수", "우천 시 감속 운행"]'::jsonb,
  '토크 센서 도심 커뮤터에 맞춘 Mokwheel Asphalt 전기자전거.',
  '2.0',
  FALSE,
  '통합 LED/디스플레이 잔량 확인',
  '[]'::jsonb,
  1300000,
  1750000,
  NULL,
  7,
  48,
  706,
  500,
  159,
  5,
  FALSE
),
(
  'draft',
  'ebike',
  'Ride1Up',
  'Ride1Up Vorsa 48V (15Ah)',
  'ride1up-vorsa-48v-15ah',
  2288000,
  560000,
  27.5,
  '전방 100mm 코일(유압 록아웃)',
  48,
  29.5,
  '["모듈러 랙·악세서리 볼트 풀림 주기 점검 필요", "안장 장거리 편안함은 호불호", "디스플레이 초기 불량 교환 사례 일부"]'::jsonb,
  '[{"title": "삼성 셀 15Ah 배터리", "description": "UL2271 배터리 잠금·CanBus SOC·외관 팽창 확인"}, {"title": "듀얼 센서 PAS", "description": "토크/케이던스 모드 전환과 스로틀 응답 점검"}, {"title": "유압 브레이크·랙", "description": "203/180mm 로터 제동과 150lb 리어랙 고정 상태"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  750,
  15,
  97,
  45,
  'Star Union 유압 디스크',
  '["토크+케이던스 듀얼센서와 커스텀 컬러 디스플레이", "440lb 페이로드·모듈러 랙으로 SUV형 활용도", "UL2849 인증과 가성비 구성"]'::jsonb,
  '["기본 무게가 있어 들어올리기 부담", "악세서리 풀옵션 시 가격 상승", "국내 공식 유통·AS 제한"]'::jsonb,
  '전장 약 182cm / 27.5×2.2–2.6',
  '전용 48V 충전기',
  2024,
  '["헬멧 착용", "클래스 설정은 현지법 준수", "동승·적재 시 랙 하중 준수"]'::jsonb,
  '모듈러 SUV형 올라운더, Ride1Up Vorsa 전기자전거.',
  NULL,
  TRUE,
  '컬러 디스플레이 및 Find My 연동 상태 확인',
  '[]'::jsonb,
  1500000,
  2000000,
  NULL,
  6,
  48,
  720,
  750,
  200,
  6,
  TRUE
),
(
  'draft',
  'kickboard',
  'VSETT',
  'VSETT 11+ 60V (31.2Ah)',
  'vsett-11-plus-60v-31-2ah',
  4319000,
  950000,
  11,
  '전후 유압 서스펜션',
  60,
  58,
  '["고속·고하중 모델이라 스템·접이부 정기 점검 필수", "중량 58kg로 휴대 불가에 가까움", "컨트롤러·모터 발열 관리 실패 시 출력 제한 가능"]'::jsonb,
  '[{"title": "60V 대용량 배터리", "description": "31.2Ah 팩 팽창·셀 밸런스·충전 중 이상발열 확인"}, {"title": "듀얼 1500W 모터", "description": "좌우 모터 출력 균형·이상음·방수 커넥터 상태"}, {"title": "유압 디스크+ABS", "description": "전후 유압 디스크와 전자 ABS·NFC 잠금 동작 점검"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  3000,
  31.2,
  160,
  70,
  '전후 유압 디스크 + 전자 ABS',
  '["듀얼 1500W와 60V 대용량으로 고성능 장거리", "유압 서스·11인치 타이어로 승차감 우수", "NFC 잠금·턴시그널 등 장비 충실"]'::jsonb,
  '["무게·가격 부담이 큼", "국내 도로 법적 최고속·출력 제한과 크게 상충", "정비·부품 비용이 높음"]'::jsonb,
  '펼침 1330×720×1360mm / 접힘 1330×270×620mm',
  '60V 2A×2 권장(약 8시간+)',
  2021,
  '["국내 도로 주행 시 법적 제한 속도·장치 규정 준수", "풀페이스 헬멧·보호구 권장", "우천·고속 동시 주행 자제"]'::jsonb,
  '고성능 듀얼모터 장거리 킥보드, VSETT 11+ 60V 31.2Ah.',
  '31.2Ah',
  TRUE,
  'VSETT 디스플레이 전압·잔량 및 앱(지원 시) 확인',
  '[]'::jsonb,
  2500000,
  3600000,
  NULL,
  10,
  60,
  1872,
  3000,
  120,
  8,
  TRUE
),
(
  'draft',
  'kickboard',
  'Apollo',
  'Apollo Ghost 52V (18.2Ah)',
  'apollo-ghost-52v-18-2ah',
  2024000,
  620000,
  10,
  '전후 조절식 스프링 서스펜션',
  52,
  30,
  '["단종·재고 소진으로 공식 신품 수급 어려움", "듀얼모터 고속 모델이라 스템 스트레스 누적 가능", "IP54 수준이라 장마철 침수에 취약"]'::jsonb,
  '[{"title": "52V 18.2Ah 배터리", "description": "947Wh급 팩 팽창·듀얼 충전포트 상태·전압 드롭 확인"}, {"title": "듀얼 800W 모터", "description": "전후 모터 출력 균형과 커넥터 방수 상태"}, {"title": "디스크 브레이크·서스", "description": "전후 디스크 패드 마모와 스프링 서스 유격·소음"}]'::jsonb,
  '[]'::jsonb,
  TRUE,
  2000,
  18.2,
  63,
  55,
  '전후 디스크 + 회생제동',
  '["컴팩트한 듀얼모터로 가속·언덕 성능 우수", "조절식 듀얼 스프링 서스로 승차감 좋음", "엔트리 듀얼 포지션 대비 완성도 높은 프레임"]'::jsonb,
  '["단종으로 보증·부품 수급 불리", "30kg라 휴대는 부담", "국내 도로 제한 속도와 스펙 괴리"]'::jsonb,
  '약 128×24×127cm급',
  '전용 충전기(싱글 약 12시간 / 듀얼포트 시 단축)',
  2020,
  '["헬멧·보호구 착용", "고속 모드는 사유지·허가 구간만", "빗길 감속"]'::jsonb,
  '엔트리 듀얼모터의 정석이었던 Apollo Ghost (단종).',
  NULL,
  FALSE,
  '디스플레이 전압·잔량 확인',
  '[]'::jsonb,
  900000,
  1500000,
  NULL,
  13,
  52,
  946,
  1600,
  136,
  10,
  FALSE
),
(
  'draft',
  'kickboard',
  'EMOVE',
  'EMOVE Touring 48V (13Ah)',
  'emove-touring-48v-13ah',
  1214000,
  420000,
  8,
  '전방 트리플 + 후방 듀얼 스프링',
  48,
  17.7,
  '["후방 솔리드 타이어는 승차감·그립이 공기입 대비 떨어짐", "스퀘어웨이브 컨트롤러로 고속에서 소음·발열", "구형 8인치 튜블리스 개량 전후 개체 차이"]'::jsonb,
  '[{"title": "LG 48V 13Ah 배터리", "description": "624Wh LG 셀 팩 팽창·GX16 충전포트 헐거움 확인"}, {"title": "500W 리어 허브", "description": "모터 베어링 소음·전원 컷오프·스로틀 유격"}, {"title": "접이·서스펜션", "description": "스템 접이 잠금과 전후 스프링 서스 유격·파손"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  750,
  13,
  40,
  39,
  '후방 드럼',
  '["풀서스임에도 18kg대 휴대성", "LG 배터리와 24mph급 실용 속도", "접이식 핸들·가변 스템으로 보관 용이"]'::jsonb,
  '["후방 솔리드 타이어 승차감 한계", "드럼 브레이크는 고속·빗길에서 디스크 대비 약함", "신형 Cruiser V2 대비 스펙 노후"]'::jsonb,
  '펼침 약 119×56×122cm / 접힘 약 109×20×29cm',
  'GX16-3P 전용 (약 6–7시간)',
  2019,
  '["헬멧 착용", "보도 주행 금지 등 현지 PM 규정 준수", "빗길·과속 금지"]'::jsonb,
  '가벼우면서 풀서스를 갖춘 커뮤터 킥보드, EMOVE Touring.',
  NULL,
  FALSE,
  'LCD 전압·트립 미터로 잔량 추정',
  '[]'::jsonb,
  450000,
  850000,
  NULL,
  10,
  48,
  624,
  500,
  140,
  6.5,
  FALSE
),
(
  'draft',
  'kickboard',
  'Segway Ninebot',
  '나인봇 F40 36V (10.2Ah)',
  'ninebot-f40-36v-10-2ah',
  750000,
  280000,
  10,
  '없음(대형 타이어로 보완)',
  36,
  15.8,
  '["서스펜션 부재로 노면 진동 전달", "배터리 내장형이라 교체 비용·난이도 상승", "장기간 사용 시 접이 힌지 유격"]'::jsonb,
  '[{"title": "내장 36V 10.2Ah", "description": "충전 이상·앱 SOC 급감·팽창 징후(덱 변형) 확인"}, {"title": "접이 메커니즘", "description": "스템 잠금 훅·유격·주행 중 흔들림"}, {"title": "타이어·브레이크", "description": "10인치 타이어 마모·공기압과 전자/기계 제동"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  350,
  10.2,
  40,
  30,
  '전자제동 + 기계식',
  '["15.8kg 내외로 출퇴근 휴대성 우수", "Ninebot 앱 연동과 안정적 품질", "10인치 휠로 F 시리즈 중 승차감 양호"]'::jsonb,
  '["서스 없음", "출력·속도가 고성능 모델 대비 낮음", "배터리 내장 교체비 부담"]'::jsonb,
  'F 시리즈 폴딩 킥보드 표준',
  '전용 42V급 충전기',
  2021,
  '["전동킥보드 헬멧 의무", "원동기 면허·보험 등 현행법 준수", "야간 등화류 점등"]'::jsonb,
  '가볍고 무난한 출퇴근형, 세그웨이 나인봇 F40.',
  'F40',
  TRUE,
  'Ninebot 앱 및 디스플레이 잔량 확인',
  '[]'::jsonb,
  300000,
  550000,
  NULL,
  10,
  36,
  367,
  350,
  120,
  6.5,
  TRUE
),
(
  'draft',
  'kickboard',
  'Pure Electric',
  'Pure Air 4 Pro 37V (9.6Ah)',
  'pure-air-4-pro-37v-9-6ah',
  970000,
  320000,
  10,
  '없음(스티어링 스태빌라이저)',
  37,
  17,
  '["서스 부재로 노면 충격 직접 전달", "UK/EU 25km/h 리밋 펌웨어", "국내 정식 유통·AS 제한"]'::jsonb,
  '[{"title": "37V 9.6Ah 배터리", "description": "잔량 급감·충전 6시간 이상 지연·팽창 여부"}, {"title": "Pure Control 스티어링", "description": "핸들 떨림 감쇠 장치 유격·이상 소음"}, {"title": "드럼+KERS", "description": "전방 드럼과 후방 회생제동 작동"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  710,
  9.6,
  40,
  25,
  '전방 드럼 + 후방 KERS',
  '["IP65 방수와 턴시그널 등 안전 장비", "Pure Control로 핸들 흔들림 감소", "710W 피크로 Air4 라인 중 언덕 성능 양호"]'::jsonb,
  '["최고 25km/h로 체감 속도 낮음", "서스펜션 없음", "국내 서비스·부품 수급 불리"]'::jsonb,
  '펼침 111×55×113cm / 접힘 111×55×48cm',
  '42V 2A (약 6시간)',
  2024,
  '["헬멧 착용", "보도 주행 금지 등 현지법 준수", "빗길에도 IP65이나 감속 운행"]'::jsonb,
  '방수와 안정장치 중심의 도심형, Pure Electric Air⁴ Pro.',
  'Air⁴ Pro',
  TRUE,
  'LCD 및 Pure 앱 잔량 확인',
  '[]'::jsonb,
  400000,
  700000,
  NULL,
  11,
  37,
  355,
  500,
  120,
  6,
  TRUE
),
(
  'draft',
  'unicycle',
  'Begode',
  'Begode A5 84V (1100Wh)',
  'begode-a5-84v-1100wh',
  1889000,
  850000,
  15,
  '없음',
  84,
  22.7,
  '["서스 없는 고밀도 팩이라 노면 충격이 무릎·발목으로 전달", "소형 EUC 특성상 고속 안정감은 대형 휠 대비 낮음", "애프터마켓 부품·국내 정비처 제한"]'::jsonb,
  '[{"title": "84V 1100Wh 팩", "description": "셀 팽창·밸런스·충전 중 온도 이상 여부"}, {"title": "모터·타이어", "description": "1500W급 모터 베어링 소음과 15인치 타이어 마모·펑크"}, {"title": "틸트백·알람", "description": "과속 알람·틸트백·트롤리 핸들 잠금 동작"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  1500,
  13.1,
  40,
  63,
  '회생제동(전자)',
  '["컴팩트 대비 1100Wh로 실용 거리 확보", "트롤리 핸들·LED·스피커 등 편의 장비", "IP67 표기로 생활 방진·방수 양호"]'::jsonb,
  '["서스펜션 없음", "초보에게 학습 곡선 가파름", "국내 도로 이륜/PM 분류와 충돌 가능"]'::jsonb,
  '15인치 휠 컴팩트 EUC',
  '84V 계열 전용 충전기',
  2024,
  '["전용 보호구·헬멧 필수", "공도 고속 주행 금지·사유지 연습 권장", "배터리 항공 운송 규정 준수"]'::jsonb,
  '컴팩트 고밀도 팩의 도심 EUC, Begode A5.',
  'A5',
  TRUE,
  'Begode 앱 전압·셀 전압 편차 확인',
  '[]'::jsonb,
  1100000,
  1600000,
  NULL,
  10,
  84,
  1100,
  1200,
  120,
  5,
  TRUE
),
(
  'draft',
  'unicycle',
  'NOSFET',
  'NOSFET Apex 151.2V (2700Wh)',
  'nosfet-apex-151-2v-2700wh',
  4521000,
  1800000,
  20,
  '프로그레시브 링키지(에어/코일 선택, 다단 조절)',
  151.2,
  38.8,
  '["38kg대 헤비급으로 운반·계단 이동 불가에 가까움", "고전압·고출력으로 세팅 미숙 시 컷아웃 위험", "서스 링키지·스탠션 정기 정비 필요"]'::jsonb,
  '[{"title": "151.2V 2700Wh 50S 팩", "description": "셀 팽창·고전압 커넥터·충전(5A) 중 발열 확인"}, {"title": "서스펜션 링크", "description": "7단 조절 위치·에어/코일 누유·유격·스탠션 스크래치"}, {"title": "듀얼보드 컨트롤러", "description": "펌웨어·알람·틸트백·모터 이상음 점검"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  8000,
  17.9,
  100,
  90,
  '회생제동(전자)',
  '["2700Wh·8000W 피크의 하이엔드 퍼포먼스", "프로그레시브 서스로 점프·오프로드 대응", "레이스 지향 소프트웨어 튜닝"]'::jsonb,
  '["가격·무게 최고 수준", "숙련자용으로 초보 부적합", "국내 공도 사용과 스펙이 크게 상충"]'::jsonb,
  '20×2.75-14 타이어 / 약 39kg',
  '151.2V 5A GX20 (약 4시간)',
  2025,
  '["트랙·사유지 외 고속 주행 금지", "풀 아머·헬멧 필수", "고전압 배터리 취급 주의"]'::jsonb,
  '레이스·오프로드용 하이엔드 EUC, NOSFET Apex 2700Wh.',
  '2700Wh 50S',
  TRUE,
  'NOSFET 앱/디스플레이 팩 전압·셀 모니터링',
  '[]'::jsonb,
  3000000,
  4000000,
  NULL,
  19,
  151.2,
  2700,
  3200,
  120,
  4,
  TRUE
),
(
  'draft',
  'scooter',
  'Segway',
  'Segway X260 60V (32Ah)',
  'segway-x260-60v-32ah',
  6075000,
  1100000,
  19,
  '전후 서스펜션(오프로드 Dirt eBike)',
  60,
  55,
  '["Dirt eBike 특성상 체인·스프로킷 마모 빠름", "55kg+로 차량 적재 장비 필요", "공도 등록·보험 이슈가 큰 고출력 모델"]'::jsonb,
  '[{"title": "60V 32Ah 배터리", "description": "팩 잠금·커넥터·팽창·잔량 정확도 확인"}, {"title": "모터·컨트롤러", "description": "5kW급 피크 출력 시 이상음·에러코드·방수 커넥터"}, {"title": "서스·브레이크·타이어", "description": "오프로드 타이어 노면 마모·브레이크 패드·포크 누유"}]'::jsonb,
  '[]'::jsonb,
  FALSE,
  5000,
  32,
  120,
  75,
  '유압 디스크',
  '["Sur-Ron급 포지션의 세그웨이 오프로드 전기 바이크", "60V 32Ah로 장거리 트레일 가능", "브랜드 부품·매뉴얼 접근성"]'::jsonb,
  '["가격이 매우 높음", "공도 합법 주행이 어렵거나 별도 등록 필요", "정비·타이어 비용이 킥보드 대비 큼"]'::jsonb,
  'Dirt eBike 풀사이즈 / 약 55kg',
  '전용 60V 계열 충전기',
  2021,
  '["사유지·허가 코스 외 고속 주행 금지", "헬멧·보호구 필수", "배터리·고전압 취급 주의"]'::jsonb,
  '세그웨이의 오프로드 전기 더트바이크 X260.',
  'X260',
  TRUE,
  '계기판 및 Segway 앱(지원 시) 잔량 확인',
  '[]'::jsonb,
  3500000,
  5200000,
  NULL,
  10,
  60,
  1920,
  3000,
  100,
  6,
  TRUE
)
ON CONFLICT (slug) DO UPDATE SET
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  manufacturer = EXCLUDED.manufacturer,
  model_name = EXCLUDED.model_name,
  original_price = EXCLUDED.original_price,
  battery_replace_cost = EXCLUDED.battery_replace_cost,
  tire_size = EXCLUDED.tire_size,
  suspension_type = EXCLUDED.suspension_type,
  battery_voltage = EXCLUDED.battery_voltage,
  weight = EXCLUDED.weight,
  chronic_defects = EXCLUDED.chronic_defects,
  used_checklist = EXCLUDED.used_checklist,
  affiliate_links = EXCLUDED.affiliate_links,
  is_discontinued = EXCLUDED.is_discontinued,
  motor_power_peak = EXCLUDED.motor_power_peak,
  battery_capacity = EXCLUDED.battery_capacity,
  range_official = EXCLUDED.range_official,
  max_speed = EXCLUDED.max_speed,
  brake_type = EXCLUDED.brake_type,
  pros = EXCLUDED.pros,
  cons = EXCLUDED.cons,
  dimensions = EXCLUDED.dimensions,
  charger_spec = EXCLUDED.charger_spec,
  release_year = EXCLUDED.release_year,
  safety_rules = EXCLUDED.safety_rules,
  one_line_summary = EXCLUDED.one_line_summary,
  sub_model = EXCLUDED.sub_model,
  bluetooth_enabled = EXCLUDED.bluetooth_enabled,
  battery_check_method = EXCLUDED.battery_check_method,
  compatible_accessories = EXCLUDED.compatible_accessories,
  used_price_min = EXCLUDED.used_price_min,
  used_price_max = EXCLUDED.used_price_max,
  image_url = EXCLUDED.image_url,
  pm_score = EXCLUDED.pm_score,
  nominal_voltage = EXCLUDED.nominal_voltage,
  battery_wh = EXCLUDED.battery_wh,
  motor_power_rated = EXCLUDED.motor_power_rated,
  max_load = EXCLUDED.max_load,
  charge_time = EXCLUDED.charge_time,
  app_integration_available = EXCLUDED.app_integration_available;

INSERT INTO public.pm_model_sources (
  pm_model_slug, source_type, source_name, source_url, verified_field, raw_value, normalized_value, evidence_summary, verification_status, source_priority, memo
) VALUES
('aventon-pace-4-36v-20ah', 'official', 'Aventon Pace 4 공식', 'https://www.aventon.com/products/pace-4-step-through-ebike', 'battery_wh', '36V 20Ah 733Wh LG', '733Wh', '공식 스펙에 36V 20Ah 733Wh·500W·70마일 표기', 'verified', 1, NULL),
('aventon-pace-4-36v-20ah', 'review', 'Florida Bicycling Pace 4', 'https://www.floridabicycling.com/2026/04/30/aventon-pace-4-step-through-ebike/', 'original_price', '$1599', '2159000 KRW', '리테일·리뷰 기준 USD 1599를 KRW 환산', 'uncertain', 2, 'USD≈1350원 환율 추정 환산'),
('aventon-pace-4-36v-20ah', 'review', 'eBikeGearLab Class 2', 'https://ebikegearlab.com/best/best-class-2-electric-bike/', 'motor_power_rated', '500W hub', '500W', 'Class 2 비교 기사에서 Pace 4 스펙 인용', 'verified', 3, NULL),
('super73-s2-se-48v-15ah', 'official', 'SUPER73-S2 SE 공식', 'https://super73.com/products/super73-s2-se-legacy', 'battery_wh', '720Wh 48V 15Ah', '720Wh', '공식 스펙 720Wh·750W nominal·$3145', 'verified', 1, NULL),
('super73-s2-se-48v-15ah', 'retailer', 'EZE Ryders S2 SE', 'https://ezeryders.com/collections/super73-ebikes-available-for-shipping/products/ebike-super73-s2-se-blackout-in-a-box', 'weight', '71 lbs', '32.2kg', '리테일러 스펙 표 71lbs·35-45 miles', 'verified', 2, NULL),
('super73-s2-se-48v-15ah', 'retailer', 'REVRides S2 SE', 'https://revrides.com/products/super73-s2-se', 'motor_power_rated', '750w nominal', '750W', '리테일러 스펙 모터·배터리 일치', 'verified', 3, NULL),
('lectric-one-48v-14ah', 'official', 'Lectric ONE 소개 블로그', 'https://lectricebikes.com/blogs/blog/introducing-the-lectric-one', 'motor_power_peak', '1310W peak / 750W', '1310W', '공식 소개글 모터·배터리 설명', 'verified', 1, NULL),
('lectric-one-48v-14ah', 'retailer', 'Beacon eBikes Lectric ONE', 'https://beaconebikes.com/products/lectric-one-long-range-ebike', 'battery_capacity', '48V 14Ah 672Wh', '14Ah', '리테일러 상세 스펙', 'verified', 2, NULL),
('lectric-one-48v-14ah', 'retailer', 'BOJ E-Bikes Lectric ONE', 'https://boj-e-bikes.com/product/lectric-one/', 'original_price', '$2399', '3239000 KRW', 'USD 2399 KRW 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산'),
('radpower-radcity-5-plus-48v-14ah', 'review', 'Electric Bike Report RadCity 5 Plus', 'https://electricbikereport.com/rad-power-bikes-radcity-5-plus-review/', 'battery_wh', '48V 14Ah 672Wh', '672Wh', '실측 리뷰 전기 스펙 섹션', 'verified', 1, NULL),
('radpower-radcity-5-plus-48v-14ah', 'review', 'Electric Bike Review RadCity 5 Plus', 'https://electricbikereview.com/rad-power-bikes/radcity-5-plus/', 'motor_power_rated', '750W', '750W', '전문 리뷰 모터·가격대 확인', 'verified', 2, NULL),
('radpower-radcity-5-plus-48v-14ah', 'review', 'Tom''s Guide RadCity 5 Plus', 'https://www.tomsguide.com/reviews/rad-power-radcity-5-plus', 'original_price', '$1499–1999', '2295000 KRW', '시세 구간 중 USD 1699 가정 환산', 'uncertain', 3, '단종·할인 시세 변동, USD 환산 추정'),
('himiway-cobra-d7-48v-20ah', 'official', 'Himiway D7 Cobra 공식', 'https://himiwaybike.com/products/himiway-d7-cobra-electric-hunting-bike', 'battery_wh', '48V 20Ah 960Wh', '960Wh', '공식 스펙 1000W·960Wh·88.6lb', 'verified', 1, NULL),
('himiway-cobra-d7-48v-20ah', 'official', 'Himiway Cobra CA', 'https://ca.himiwaybike.com/products/himiway-electric-mountain-bike', 'motor_power_rated', '1000W', '1000W', '캐나다 공식 페이지 모터·배터리', 'verified', 2, NULL),
('himiway-cobra-d7-48v-20ah', 'review', 'eBike Generation Himiway guide', 'https://ebikegeneration.com/blogs/news/himiway-electric-bikes-guide', 'original_price', '$2499', '3374000 KRW', 'USD 2499 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산'),
('mokwheel-asphalt-2-0-48v-14-7ah', 'official', 'Mokwheel Asphalt 공식', 'https://www.mokwheel.com/products/asphalt', 'battery_capacity', '48V 14.7A', '14.7Ah', '공식 Technical 섹션', 'verified', 1, NULL),
('mokwheel-asphalt-2-0-48v-14-7ah', 'retailer', 'EZE Ryders Asphalt 2.0', 'https://ezeryders.com/products/mokwheel-asphalt-2-0', 'motor_power_peak', '860W peak', '860W', '리테일러 피크 출력·가격', 'verified', 2, NULL),
('mokwheel-asphalt-2-0-48v-14-7ah', 'official', 'Mokwheel Asphalt 가격', 'https://www.mokwheel.com/products/asphalt', 'original_price', '$1499.99', '2024000 KRW', '공식 판매가 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산'),
('ride1up-vorsa-48v-15ah', 'official', 'Ride1Up Vorsa 공식', 'https://ride1up.com/product/vorsa/', 'battery_capacity', '15Ah Samsung', '15Ah', '공식 컴포넌트 스펙', 'verified', 1, NULL),
('ride1up-vorsa-48v-15ah', 'official', 'Meet the Vorsa', 'https://ride1up.com/blogs/meet-the-vorsa/', 'motor_power_rated', '750W 95Nm', '750W', '공식 소개 모터·토크', 'verified', 2, NULL),
('ride1up-vorsa-48v-15ah', 'review', 'Electric Bike Review Vorsa', 'https://electricbikereview.com/ride1up/vorsa-review/', 'original_price', '$1695', '2288000 KRW', '리뷰·공식 $1695 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산'),
('vsett-11-plus-60v-31-2ah', 'official', 'VSETT 11+ 공식', 'https://vsettscooters.com/pages/vsett-11-plus', 'battery_capacity', '60V 31.2AH', '31.2Ah', '공식 스펙 표', 'verified', 1, NULL),
('vsett-11-plus-60v-31-2ah', 'review', 'Freshly Charged VSETT 11+', 'https://www.freshlycharged.com/reviews/46/vsett-11-electric-scooter-review', 'max_speed', '50-53 mph sport', '70km/h', '리뷰 최고속·가격대', 'verified', 2, NULL),
('vsett-11-plus-60v-31-2ah', 'retailer', 'Levy compare VSETT 11+', 'https://www.levyelectric.com/compare-scooters/compare-the-vsett-11+-and-the-kaabo-wolf-warrior-11', 'original_price', '~$3199', '4319000 KRW', '비교 페이지 가격대 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산'),
('apollo-ghost-52v-18-2ah', 'official', 'Apollo Ghost 공식 블로그', 'https://apolloscooters.co/blogs/news/apollo-ghost-best-adult-electric-scooter', 'battery_capacity', '52V 18.2Ah 947Wh', '18.2Ah', '공식 소개 듀얼 800W·52V 18.2Ah', 'verified', 1, NULL),
('apollo-ghost-52v-18-2ah', 'review', 'ScooterRank Apollo Ghost', 'https://scooterrank.com/scooters/apollo-ghost', 'max_speed', '54.7 km/h', '55km/h', '집계 스펙 최고속·중량', 'verified', 2, NULL),
('apollo-ghost-52v-18-2ah', 'review', 'Electrek Apollo Ghost', 'https://electrek.co/2021/01/25/apollo-ghost-review-testing-a-34-mph-electric-scooter-with-better-suspension-than-my-first-car/', 'original_price', '~$1499–1699', '2024000 KRW', '단종 시세·리뷰 가격 환산', 'uncertain', 3, '단종 모델, USD 환산 추정'),
('emove-touring-48v-13ah', 'official', 'VORO Helpcenter Touring Specs', 'https://helpcenter.voromotors.com/en-US/general-specifications-6530422', 'battery_wh', '48V 13AH LG 624Wh', '624Wh', '공식 헬프센터 스펙', 'verified', 1, NULL),
('emove-touring-48v-13ah', 'review', 'Electrek EMOVE Touring', 'https://electrek.co/2020/01/14/review-emove-touring-electric-scooter-full-suspension-commuter/', 'motor_power_peak', '750W peak', '750W', '실측 리뷰 스펙·$899', 'verified', 2, NULL),
('emove-touring-48v-13ah', 'review', 'VORO Touring maintenance', 'https://www.voromotors.com/blogs/news/emove-touring-electric-scooter-maintenance-guide', 'original_price', '$899', '1214000 KRW', '정가 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산'),
('ninebot-f40-36v-10-2ah', 'official', 'Segway Support F series', 'https://support.segway.com/support_product.php?segcatid=12', 'battery_capacity', '10.2Ah class', '10.2Ah', 'Segway 서포트 F 시리즈 배터리 정보', 'verified', 1, NULL),
('ninebot-f40-36v-10-2ah', 'review', 'ScooterRank Segway F40', 'https://scooterrank.com/scooters/segway-ninebot-f40', 'range_official', '40km / 367Wh', '40km', '리뷰 집계 항속·중량', 'verified', 2, NULL),
('ninebot-f40-36v-10-2ah', 'retailer', '시장가 F40', 'https://scooterrank.com/scooters/segway-ninebot-f40', 'original_price', '~$500–800', '750000 KRW', '중저가 킥보드 시세 추정', 'uncertain', 3, '공식 정가 변동, USD 중간값 환산 추정'),
('pure-air-4-pro-37v-9-6ah', 'retailer', 'Horizon Pure Air4 Pro', 'https://horizonmicromobility.com/products/pure-electric-air-pro', 'battery_capacity', '37V 9.6Ah', '9.6Ah', '리테일러 상세 스펙·£569', 'verified', 1, NULL),
('pure-air-4-pro-37v-9-6ah', 'official', 'Pure Electric scooters', 'https://www.pureelectric.com/collections/all-electric-scooters', 'max_speed', '25 km/h', '25km/h', '브랜드 라인업·속도 제한 확인', 'verified', 2, NULL),
('pure-air-4-pro-37v-9-6ah', 'retailer', 'Horizon 가격', 'https://horizonmicromobility.com/products/pure-electric-air-pro', 'original_price', '£569', '970000 KRW', 'GBP→KRW 추정 환산', 'uncertain', 3, 'GBP≈1700원대 가정 환산, 불확실'),
('begode-a5-84v-1100wh', 'retailer', 'Ai-Rides Begode A5', 'https://www.ai-rides.com/products/begode-a5', 'battery_wh', '84V 1100Wh', '1100Wh', '리테일러 스펙 표 1100Wh·15인치', 'verified', 1, NULL),
('begode-a5-84v-1100wh', 'retailer', 'Giracat Begode A5', 'https://www.giracat.net/en/begode-a5/', 'motor_power_rated', '1500W / 1200W listings', '1200W', '판매처별 모터 표기 교차', 'verified', 2, NULL),
('begode-a5-84v-1100wh', 'retailer', 'Ai-Rides 가격', 'https://www.ai-rides.com/products/begode-a5', 'original_price', '$1399', '1889000 KRW', 'USD 1399 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산'),
('nosfet-apex-151-2v-2700wh', 'retailer', 'Top-wheel NOSFET Apex', 'https://top-wheel.com/products/nosfet-apex-electric-unicycle-151-2v-2700wh-50s-20inch-2-75-14', 'battery_wh', '151.2V 2700Wh 50S', '2700Wh', '판매 페이지 핵심 스펙', 'verified', 1, NULL),
('nosfet-apex-151-2v-2700wh', 'retailer', 'Ride+Glide Apex', 'https://www.rideandglide.co.uk/product/nosfet-apex-1000-50s-2700wh-electric-unicycle-copy/', 'motor_power_peak', '8000W peak', '8000W', 'UK 리테일러 모터·서스 스펙', 'verified', 2, NULL),
('nosfet-apex-151-2v-2700wh', 'retailer', 'Top-wheel 가격', 'https://top-wheel.com/products/nosfet-apex-electric-unicycle-151-2v-2700wh-50s-20inch-2-75-14', 'original_price', '$3349', '4521000 KRW', 'USD 3349 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산'),
('segway-x260-60v-32ah', 'official', 'Segway Support X160/X260', 'https://support.segway.com/support_product.php?segcatid=50', 'battery_capacity', '60V 32Ah', '32Ah', 'Segway 서포트 Dirt eBike 스펙', 'verified', 1, NULL),
('segway-x260-60v-32ah', 'retailer', 'Lithium Powersports X260', 'https://lithiumpowersports.com/products/segway-x260-electric-bike-74-6-mi-range-46-6-miles-per-hour', 'max_speed', '46.6 mph / 75km/h', '75km/h', '리테일러 최고속·항속', 'verified', 2, NULL),
('segway-x260-60v-32ah', 'retailer', 'Lithium Powersports 가격', 'https://lithiumpowersports.com/products/segway-x260-electric-bike-74-6-mi-range-46-6-miles-per-hour', 'original_price', '~$4499–4999', '6075000 KRW', 'USD 약 4500 환산', 'uncertain', 3, 'USD≈1350원 환율 추정 환산')
ON CONFLICT ON CONSTRAINT "unique_pm_model_source_evidence" DO UPDATE SET
  source_name = EXCLUDED.source_name,
  raw_value = EXCLUDED.raw_value,
  normalized_value = EXCLUDED.normalized_value,
  evidence_summary = EXCLUDED.evidence_summary,
  verification_status = EXCLUDED.verification_status,
  source_priority = EXCLUDED.source_priority,
  memo = EXCLUDED.memo;
